name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t iom996/uptimebot .

      - name: token
        run: echo "token=${{secrets.token}}" > .env

      - name: Run container
        run: docker run iom996/uptimebot
